version: '3.8'

services:
  redis-cluster-creator:
    user: root
    container_name: redis-cluster-creator
    image: docker.io/bitnami/redis-cluster:7.0.8
    ports:
      - 30000:6379
    volumes:
      - ./redis-cluster_creator:/bitnami/redis/data
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-cluster-creator redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
    env_file:
      - .env
    networks:
      redis-cluster-network:
        ipv4_address: 192.168.88.2
    restart: always

  redis-node-0:
    user: root
    container_name: redis-node-0
    image: docker.io/bitnami/redis-cluster:7.0.8
    ports:
      - 30001:6379
    volumes:
      - ./redis-cluster_data-0:/bitnami/redis/data
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-cluster-creator redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
    env_file:
      - .env
    networks:
      redis-cluster-network:
        ipv4_address: 192.168.88.3
    restart: always

  redis-node-1:
    user: root
    container_name: redis-node-1
    image: docker.io/bitnami/redis-cluster:7.0.8
    ports:
      - 30002:6379
    volumes:
      - ./redis-cluster_data-1:/bitnami/redis/data
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-cluster-creator redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
    env_file:
      - .env
    networks:
      redis-cluster-network:
        ipv4_address: 192.168.88.4
    restart: always

  redis-node-2:
    user: root
    container_name: redis-node-2
    image: docker.io/bitnami/redis-cluster:7.0.8
    ports:
      - 30003:6379
    volumes:
      - ./redis-cluster_data-2:/bitnami/redis/data
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-cluster-creator redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
    env_file:
      - .env
    networks:
      redis-cluster-network:
        ipv4_address: 192.168.88.5
    restart: always

  redis-node-3:
    user: root
    container_name: redis-node-3
    image: docker.io/bitnami/redis-cluster:7.0.8
    ports:
      - 30004:6379
    volumes:
      - ./redis-cluster_data-3:/bitnami/redis/data
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-cluster-creator redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
    env_file:
      - .env
    networks:
      redis-cluster-network:
        ipv4_address: 192.168.88.6
    restart: always

  redis-node-4:
    user: root
    container_name: redis-node-4
    image: docker.io/bitnami/redis-cluster:7.0.8
    ports:
      - 30005:6379
    volumes:
      - ./redis-cluster_data-4:/bitnami/redis/data
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-cluster-creator redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
    env_file:
      - .env
    networks:
      redis-cluster-network:
        ipv4_address: 192.168.88.7

networks:
  redis-cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.88.0/24

volumes:
  redis-cluster_creator:
    driver: local
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
